#!/usr/bin/env bash
#Script creating file, display messsage and delete file

sigterm_handler()
{
	echo "I hate the kill command"
}
sigint_handler()
{
	echo "Y U no love me?!"
}
sigquit_handler()
{
	rm -f /var/run/myscript.pid
	exit 0
}
trap 'sigterm_handler' SIGTERM
trap 'sigint_handler' SIGINT
trap 'sigquit_handler' SIGQUIT

echo $$ > /var/run/myscript.pid

while true; do
	echo "To infinity and beyond"
	sleep 2
done

