#!/usr/bin/env bash
#Displays 4-to_infinity_and_beyond indefinitely with slepp 2 anda sigterm signal

sigterm_handler()
{
	echo "I am invincible!!!"
	exit 0
}
trap 'sigterm_handler' SIGTERM
while true; do
	echo "To infinity and beyond"
	sleep 2
done
