#!/usr/bin/env bash
#Displays Best School ten times with 9th iteration being Hi

counter=1

while [ $counter -le 10 ]
do
    if [ $counter -eq 9 ]
    then
        echo "Best School"
        echo "Hi"
    else
        echo "Best School"
    fi

    ((counter++))
done
